[package]
name    = "slice-tracker"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
license = "BSD-2-Clause"

edition = "2018"

[dependencies]
memchr = "2.3.3"

[dev-dependencies]
assert2 = "0.1.2"
